files:
  - source: /src/locales/en-UK/*.json
    type: i18next_json
    translation: /src/locales/%locale%/%original_file_name%
export_languages:
  - de
  - en
  - es
  - fr
  - it
  - ja
  - ko
  - lt
  - nl
  - pl
  - pt-BR
  - ro
  - ru
  - sv
commit_message: '[skip-ci]'
