<?php include('_includes/bootstrap.php'); ?><!doctype html>
<html class=" js websqldatabase draganddrop cssscrollbar" lang="en">
<head>
    <?php include('includes/meta/LU_meta.php'); ?>
</head>
<body>
<div id="container" class="page settings mfa">
    <div class="mad_event_event_bus"></div>
    <div id="js_app_controller" class="passbolt_controller_app_controller mad_view_view js_component ready">
        <?php include('includes/headers/LU_header_first.php'); ?>
        <div class="header second">
            <?php include('includes/headers/LU_header_second_logo.php'); ?>
            <?php include('includes/headers/LU_header_search_users.php'); ?>
            <?php include('includes/headers/LU_header_userbadge.php'); ?>
        </div>
        <div class="header third">
            <!-- no actions -->
        </div>
        <div class="panel main mad_controller_component_tab_controller mad_view_component_tab js_component ready" id="js_app_panel_main">
            <div class="js_tabs_content tabs-content">
                <div id="js_passbolt_preferenceWorkspace_controller" class="passbolt_controller_preference_workspace_controller mad_view_view tab-content ready selected">
                    <div class="js_preference_workspace">
                        <div class="panel left">
                            <?php
                            $_GET['shortcuts'] = 'loginhistory';
                            include('includes/nav/LU_nav_shortcuts_profile.php');
                            ?>
                        </div>
                        <div class="panel middle">
                            <?php
                            $_GET['breadcrumbs'] = array(
                                'profile' => '../demo/LU_users_profile.php',
                                'second factor authentication' => '../demo/LU_users_profile_mfa_01.php',
                                'setup' => '../demo/LU_users_profile_mfa_02.php'
                            );
                            include('includes/LU_breadcrumbs.php'); ?>

                            <div class="mfa wizard verify">
                                <form>
                                <div class="grid grid-responsive-12">
                                    <div class="row">
                                        <div class="col6 last">
                                            <h3>Multi factor authentication is enabled!</h3>
                                            <div class="success message animated">
                                                <div class="illustration">
                                                    <svg id="successAnimation" class="animated" xmlns="http://www.w3.org/2000/svg" width="170" height="170" viewBox="0 0 70 70">
                                                        <circle id="successAnimationCircle" cx="35" cy="35" r="24" stroke="#000000" stroke-width="3" stroke-linecap="round" fill="transparent"/>
                                                        <polyline id="successAnimationCheck" stroke="#000000" stroke-width="3" points="23 34 34 43 47 27" linecap="round" fill="transparent"/>
                                                    </svg>
                                                </div>
                                                <div class="additional-information">
                                                <p>
                                                    When loggin from a new device you will need to
                                                    enter a unique verification code generated by an app on your mobile
                                                </p>
                                                <p class="created date">
                                                    Added: Sep 12, 6:45 PM.
                                                </p>
                                                <p>
                                                    <a class="button warning big" href="../demo/LU_users_profile_mfa_01.php">Turn off</a>
                                                </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php include('includes/LU_footer.php'); ?>
</body>
</html>