<div class="dialog-wrapper ready">
	<div class="dialog export">
		<div class="dialog-header">
			<h2>Export passwords</h2>
			<a href="../demo/LU_passwords.php" class="dialog-close">
				<i class="fa fa-close"></i><span class="visuallyhidden">close</span>
			</a>

		</div>
		<div class="js_dialog_content dialog-content">
			<form
				action="../demo/LU_passwords.php"
				class="tab-content ready selected"
				id="js_rs_export">
				<div class="form-content">
					<div class="input select required">
						<label for="">Choose the export format (
							<a role="link" data-tooltip="csv export format is compatible with the one of keepassx">csv</a> and
							<a role="link" data-tooltip="kdbx files are files generated by keepass v2.x">kdbx are supported)</a></label>
						<select>
							<option>kdbx (keepass / keepassx)</option>
							<option>csv (comma separated values)</option>
						</select>

					</div>
					<p><br><em>28 passwords are going to be exported.</em></p>
				</div>
				<div class="submit-wrapper clearfix">
					<input class="button primary" value="Export" type="submit" onclick="javascript:window.location.href='../demo/LU_passwords.php'; return false;">
				</div>
			</form>
		</div>
	</div>
</div>