<div class="dialog-wrapper ready">
	<div class="dialog import">
		<div class="dialog-header">
			<h2>Import passwords</h2>
			<a href="demo/LU_passwords.php" class="dialog-close">
			<span class="fa icon">
                    <svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1490 1322q0 40-28 68l-136 136q-28 28-68 28t-68-28l-294-294-294 294q-28 28-68 28t-68-28l-136-136q-28-28-28-68t28-68l294-294-294-294q-28-28-28-68t28-68l136-136q28-28 68-28t68 28l294 294 294-294q28-28 68-28t68 28l136 136q28 28 28 68t-28 68l-294 294 294 294q28 28 28 68z"/></svg>
								</span>
								<span class="visuallyhidden">close</span>
			</a>

		</div>
		<div class="dialog-content">
			<form action="demo/LU_passwords.php" id="js_rs_import">
				<div class="form-content">
					<div class="input text required error">
						<label>
							Select a file to import
							(<a role="link" data-tooltip="csv exports from keepassx, lastpass and 1password are supported">csv</a>
							or <a role="link" data-tooltip="kdbx files are files generated by keepass v2.x">kdbx</a>)
						</label>
						<input name="passbolt.model.Import.file"
									 class="jfilestyle"
									 id="js_field_name" placeholder="name" type="file"
                               data-text="Choose a file" data-placeholder="No file selected">

						<div id="js_field_import_feedback" class="message ready error">
							This is the error message
						</div>
					</div>
					<div class="input text">
						<input type="checkbox" name="passbolt.model.Import.category_as_tags"
						       id="js_field_category_as_tags"> <label>Import categories as tags</label>
					</div>

				</div>
				<div class="submit-wrapper clearfix">
					<input class="button primary" value="Import" type="submit" onclick="javascript:window.location.href='demo/LU_passwords_import_options.php'; return false;">
					<a href="demo/LU_passwords.php" class="js-dialog-cancel cancel">Cancel</a>
				</div>
			</form>
		</div>
	</div>
</div>